# Site settings
future: true
title: "Dotnet User Group Regensburg"
email: info@dotnet-regensburg.de
description: "Wir sind die Dotnet User Group Regensburg. Wir wollen Programmierer*innen aus Regensburg zusammenbringen, Ideen austauschen und gemeinsam lernen. Der Schwerpunkt liegt auf Dotnet, wir sind jedoch offen für alle Technologien und Methoden, die in der Softwareentwicklung relevant sind. Jeder Vortrag bietet die Möglichkeit, Neues zu lernen, Wissen zu vertiefen und sich mit neuen Trends und Methoden vertraut zu machen. Unsere Community richtet sich an alle Softwareentwickler*innen, Student*innen und Interessierten, die Lust haben, sich auszutauschen, zu vernetzen und von- und miteinander zu lernen."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2879d0
  secondary: 2268b2  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Thomas Ebert
  pic: thomas-ebert
  position: "Gründer, Organisator"
  social:
    - title: xing
      url: https://www.xing.com/profile/Thomas_Ebert23
    - title: twitter
      url: https://twitter.com/ebtom
    - title: linkedin
      url: https://de.linkedin.com/pub/thomas-ebert/21/562/13a

- name: Roland Wurm
  pic: roland-wurm
  position: Gründer
  social:
    - title: facebook
      url: https://www.facebook.com/pages/CONCEPTNET-GmbH/195439487148007
    - title: youtube
      url: https://www.youtube.com/user/conceptnet
    - title: xing
      url: https://www.xing.com/profile/Roland_Wurm4

- name: Kenny Pflug
  pic: kenny-pflug
  position: "Organisator, Sprecher"
  social:
    - title: twitter
      url: https://twitter.com/feo2x
    - title: github
      url: https://github.com/feO2x
    - title: youtube
      url: https://www.youtube.com/channel/UCfS1gb_r6GUfPd1EV82aBzg

- name: Roland König
  pic: roland-koenig
  position: "Sprecher"
  social:
    - title: rss
      url: http://www.rolandk.de/wp/
    - title: github
      url: https://github.com/RolandKoenig
    - title: facebook
      url: https://www.facebook.com/roland.konig.14

- name: Florian Rappl
  pic: florian-rappl
  position: "Website, Sprecher"
  social:
    - title: twitter
      url: https://twitter.com/FlorianRappl
    - title: github
      url: https://github.com/FlorianRappl
    - title: rss
      url: http://www.florian-rappl.de

- name: Peter Butzhammer
  pic: peter-butzhammer
  position: "Organisator, Sprecher"
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/peter-butzhammer/
    - title: github
      url: https://github.com/peter-b-
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/DotNetRegensburg

# Postal address (add as many lines as necessary)
address:
  - line: .NET Usergroup Regensburg
  - line: c/o Roland Wurm
  - line: CONCEPTNET GmbH
  - line: 93055 Regensburg

# Sponsors
sponsors:
  top:
    - name: "CONCEPTNET GmbH"
      link: http://www.conceptnet.de/
      logo: conceptnet.png
    - name: "Krones.digital"
      link: https://krones.digital
      logo: Krones.digital.png
    - name: "IT-Speicher Regensburg"
      link: http://www.it-speicher.de/
      logo: itspeicher.png
  middle:
    - name: "dotnetpro"
      link: http://www.dotnetpro.de/
      logo: dotnetpro.gif
    - name: "Pluralsight"
      link: http://www.pluralsight-training.net/
      logo: pluralsight.png
    - name: "IHK Regensburg"
      link: http://www.ihk-regensburg.de/
      logo: ihk.gif
  ads:
    - name: "initPRO GmbH"
      link: http://www.initpro.de/
      logo: initpro.jpg
    - name: "combit Software"
      link: https://www.combit.net/
      logo: combit.gif
    - name: "JetBrains ReSharper"
      link: https://www.jetbrains.com/resharper/
      logo: resharper.gif



# Build settings
markdown: kramdown
permalink: pretty
