name: Generate Calendar

on:
  push:
    branches: [ master, main ]
    paths:
      - '_posts/**'
      - 'scripts/calendar_generator/**'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  generate-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Generate and copy calendar
      run: |
        cd scripts/calendar_generator
        pip install -r requirements.txt
        python generate_calendar.py
        cp calendar.ics ../../calendar.ics
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit calendar updates
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add calendar.ics
        git commit -m "Update calendar file based on recent changes [skip ci]"
        git push
